[build]
  command = "npm run build"
  publish = ".next"

# Plugin Next.js dla Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Netlify automatycznie wykrywa Next.js i konwertuje API routes na Functions
[build.environment]
  # Nie potrzebujemy już omijania skanowania sekretów dla API routes
  NODE_VERSION = "18"

[dev]
  publish = "dist"

[[redirects]]
from = "https://www.jacht-plast.pl/transport"
to = "https://www.jacht-plast.pl/transport-jachtow"
status = 301
force = true

[[redirects]]
from = "https://www.jacht-plast.pl/production"
to = "https://www.jacht-plast.pl/produkcja-jachtow"
status = 301
force = true

[[redirects]]
from = "https://www.jacht-plast.pl/produkcja"
to = "https://www.jacht-plast.pl/produkcja-jachtow"
status = 301
force = true

[[redirects]]
from = "https://www.jacht-plast.pl/contact"
to = "https://www.jacht-plast.pl/kontakt"
status = 301
force = true